apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
