apiVersion: v1
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 131072;
      use epoll;
      multi_accept on;
    }
    http {
      tcp_nodelay on;
      include /etc/nginx/conf.d/*.upstream.conf;
      proxy_http_version 1.1;
      upstream registry {
        server 127.0.0.1:5000;
      }
      upstream ui {
        server 127.0.0.1:81;
      }
      upstream adminserver {
        server 127.0.0.1:82;
      }
      upstream jobservice {
        server 127.0.0.1:83;
      }
      log_format timed_combined '$remote_addr - '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" '
        '$request_time $upstream_response_time $pipe';
      access_log /dev/stdout timed_combined;
      include /etc/nginx/conf.d/*.server.conf;
      server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/cert/server.crt;
        ssl_certificate_key /etc/nginx/cert/server.key;
        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_ciphers '!aNULL:kECDH+AESGCM:ECDH+AESGCM:RSA+AESGCM:kECDH+AES:ECDH+AES:RSA+AES:';
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        client_max_body_size 0;
        chunked_transfer_encoding on;
        location / {
          proxy_pass http://ui/;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_cookie_path / "/; secure";
          proxy_buffering off;
          proxy_request_buffering off;
        }
        location /v1/ {
          return 404;
        }
        location /v2/ {
          proxy_pass http://registry/v2/;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_buffering off;
          proxy_request_buffering off;
        }
        location /service/ {
          proxy_pass http://ui/service/;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_buffering off;
          proxy_request_buffering off;
        }
        location /service/notifications {
          return 404;
        }
      }
      server {
          listen 80;
          server_name ~^(adminserver|ui|jobservice)$;
          location / {
            proxy_pass http://${http_host};
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cookie_path / "/; secure";
            proxy_buffering off;
            proxy_request_buffering off;
          }
      }
      server {
          listen 80;
          return 301 https://$host$request_uri;
      }
    }
kind: ConfigMap
metadata:
  name: nginx
  namespace: registry
