apiVersion: v1
kind: Service
metadata:
  labels:
    run: harbor
  name: harbor
  namespace: registry
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: harbor
  type: ClusterIP
